yarn rw g sdl AnswerComment --force
yarn rw g sdl Answer --force
yarn rw g sdl Badge --force
yarn rw g sdl Category --force
yarn rw g sdl Group --force
yarn rw g sdl Issue --force
yarn rw g sdl QuestionIsInCategory --force
yarn rw g sdl Question --force
yarn rw g sdl Sentence --force
yarn rw g sdl Translation --force
yarn rw g sdl UserHasBadges --force
yarn rw g sdl UserIsInGroup --force
yarn rw g sdl UserLikesAnswer --force
yarn rw g sdl UserLikesComment --force
yarn rw g sdl UserLikesQuestion --force
yarn rw g sdl User --force
